name: act-clip
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - act==0.1.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - arm-pytorch-utilities==0.4.3
      - asttokens==3.0.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - dacite==1.9.2
      - decorator==5.2.1
      - diffusers==0.35.2
      - docstring-parser==0.17.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fast-kinematics==0.2.2
      - filelock==3.20.0
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - gymnasium==0.29.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.7
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - mani-skill==3.0.0b21
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mplib==0.1.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.11.0.86
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - protobuf==6.33.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - python-dateutil==2.9.0.post0
      - pytorch-kinematics==0.7.6
      - pytorch-seed==0.2.0
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - safetensors==0.7.0
      - sapien==3.0.1
      - scipy==1.15.3
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - shtab==1.8.0
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - toppra==0.6.3
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transforms3d==0.4.2
      - trimesh==4.10.0
      - triton==3.5.1
      - typeguard==4.4.4
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - urllib3==2.5.0
      - wandb==0.23.1
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - zipp==3.23.0
prefix: /scratch/user/u.ho340935/.conda/envs/act-clip
